"""add card_catalog and catalog_meta tables

Revision ID: 24baa574b69d
Revises: b7e1c4d9f2a3
Create Date: 2026-07-19 11:42:09.369927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24baa574b69d'
down_revision: Union[str, Sequence[str], None] = 'b7e1c4d9f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_catalog',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('set_id', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('types', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_card_catalog_name'), 'card_catalog', ['name'], unique=False)
    op.create_index(op.f('ix_card_catalog_set_id'), 'card_catalog', ['set_id'], unique=False)
    op.create_table('catalog_meta',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_meta')
    op.drop_index(op.f('ix_card_catalog_set_id'), table_name='card_catalog')
    op.drop_index(op.f('ix_card_catalog_name'), table_name='card_catalog')
    op.drop_table('card_catalog')
    # ### end Alembic commands ###
