"""add snapshot card_id+date index

Revision ID: a520ca9cee08
Revises: 6192eacdc883
Create Date: 2026-07-14 09:31:51.228792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a520ca9cee08'
down_revision: Union[str, Sequence[str], None] = '6192eacdc883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_snapshot_card_date', 'portfolio_snapshot', ['card_id', 'snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshot_card_date', table_name='portfolio_snapshot')
    # ### end Alembic commands ###
